version: '3'
services:
  node:
    environment: 
      - AWS_PROFILE=danielle
    depends_on:
        - 'mongo'
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
    mongodb: